"""Add AI intelligence layer models

Revision ID: eb868c3e077e
Revises: 48e599f8e640
Create Date: 2026-07-22 22:16:58.301152

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb868c3e077e'
down_revision: Union[str, None] = '48e599f8e640'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('achievements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('badge_name', sa.String(length=100), nullable=False),
    sa.Column('badge_type', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_achievements_id'), 'achievements', ['id'], unique=False)
    op.create_index(op.f('ix_achievements_user_id'), 'achievements', ['user_id'], unique=False)
    op.create_table('behavior_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('analysis_date', sa.Date(), nullable=False),
    sa.Column('drift_score', sa.Float(), nullable=False),
    sa.Column('consistency_score', sa.Float(), nullable=False),
    sa.Column('lifestyle_change_index', sa.Float(), nullable=False),
    sa.Column('risk_indicators', sa.Text(), nullable=True),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_behavior_logs_analysis_date'), 'behavior_logs', ['analysis_date'], unique=False)
    op.create_index(op.f('ix_behavior_logs_id'), 'behavior_logs', ['id'], unique=False)
    op.create_index(op.f('ix_behavior_logs_user_id'), 'behavior_logs', ['user_id'], unique=False)
    op.create_table('coach_conversation_memories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Text(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_coach_conversation_memories_id'), 'coach_conversation_memories', ['id'], unique=False)
    op.create_index(op.f('ix_coach_conversation_memories_user_id'), 'coach_conversation_memories', ['user_id'], unique=False)
    op.create_table('digital_lifestyle_twins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('sleep_baseline', sa.Float(), nullable=False),
    sa.Column('activity_baseline', sa.Float(), nullable=False),
    sa.Column('screen_baseline', sa.Float(), nullable=False),
    sa.Column('mood_baseline', sa.Float(), nullable=False),
    sa.Column('wellness_score', sa.Float(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_digital_lifestyle_twins_id'), 'digital_lifestyle_twins', ['id'], unique=False)
    op.create_index(op.f('ix_digital_lifestyle_twins_snapshot_date'), 'digital_lifestyle_twins', ['snapshot_date'], unique=False)
    op.create_index(op.f('ix_digital_lifestyle_twins_user_id'), 'digital_lifestyle_twins', ['user_id'], unique=False)
    op.create_table('goals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('target_value', sa.Float(), nullable=False),
    sa.Column('current_value', sa.Float(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('target_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_goals_category'), 'goals', ['category'], unique=False)
    op.create_index(op.f('ix_goals_id'), 'goals', ['id'], unique=False)
    op.create_index(op.f('ix_goals_user_id'), 'goals', ['user_id'], unique=False)
    op.create_table('recommendations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('priority_score', sa.Float(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recommendations_category'), 'recommendations', ['category'], unique=False)
    op.create_index(op.f('ix_recommendations_id'), 'recommendations', ['id'], unique=False)
    op.create_index(op.f('ix_recommendations_user_id'), 'recommendations', ['user_id'], unique=False)
    op.create_table('stress_likelihoods',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('assessment_date', sa.Date(), nullable=False),
    sa.Column('stress_score', sa.Float(), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('contributing_factors', sa.Text(), nullable=True),
    sa.Column('recommendations', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stress_likelihoods_assessment_date'), 'stress_likelihoods', ['assessment_date'], unique=False)
    op.create_index(op.f('ix_stress_likelihoods_id'), 'stress_likelihoods', ['id'], unique=False)
    op.create_index(op.f('ix_stress_likelihoods_user_id'), 'stress_likelihoods', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stress_likelihoods_user_id'), table_name='stress_likelihoods')
    op.drop_index(op.f('ix_stress_likelihoods_id'), table_name='stress_likelihoods')
    op.drop_index(op.f('ix_stress_likelihoods_assessment_date'), table_name='stress_likelihoods')
    op.drop_table('stress_likelihoods')
    op.drop_index(op.f('ix_recommendations_user_id'), table_name='recommendations')
    op.drop_index(op.f('ix_recommendations_id'), table_name='recommendations')
    op.drop_index(op.f('ix_recommendations_category'), table_name='recommendations')
    op.drop_table('recommendations')
    op.drop_index(op.f('ix_goals_user_id'), table_name='goals')
    op.drop_index(op.f('ix_goals_id'), table_name='goals')
    op.drop_index(op.f('ix_goals_category'), table_name='goals')
    op.drop_table('goals')
    op.drop_index(op.f('ix_digital_lifestyle_twins_user_id'), table_name='digital_lifestyle_twins')
    op.drop_index(op.f('ix_digital_lifestyle_twins_snapshot_date'), table_name='digital_lifestyle_twins')
    op.drop_index(op.f('ix_digital_lifestyle_twins_id'), table_name='digital_lifestyle_twins')
    op.drop_table('digital_lifestyle_twins')
    op.drop_index(op.f('ix_coach_conversation_memories_user_id'), table_name='coach_conversation_memories')
    op.drop_index(op.f('ix_coach_conversation_memories_id'), table_name='coach_conversation_memories')
    op.drop_table('coach_conversation_memories')
    op.drop_index(op.f('ix_behavior_logs_user_id'), table_name='behavior_logs')
    op.drop_index(op.f('ix_behavior_logs_id'), table_name='behavior_logs')
    op.drop_index(op.f('ix_behavior_logs_analysis_date'), table_name='behavior_logs')
    op.drop_table('behavior_logs')
    op.drop_index(op.f('ix_achievements_user_id'), table_name='achievements')
    op.drop_index(op.f('ix_achievements_id'), table_name='achievements')
    op.drop_table('achievements')
    # ### end Alembic commands ###
